version: '2'
services:
  interface:
    extends:
      file: app.yml
      service: interface
    environment:
      - INTERACTIVE
      - LOCAL
      - SELENIUM_ADDRESS=http://selenium:4444/wd/hub
      - RAILS_ENV=test
      - APP_DOMAIN=interface
      - API_DOMAIN=http://mockserver:1080
      - MOCKSERVER_DOMAIN=mockserver
      - PORT=3002
    env_file: ../../test.env
  tester:
    build:
      context: ../..
      dockerfile: Docker/Dockerfiles/tester
    volumes_from:
      - interface
    links:
      - selenium
      - interface
      - mockserver
    depends_on:
      - interface
    environment:
      - LOCAL
      - INTERACTIVE
      - RAILS_ENV=test
      - APP_DOMAIN=interface
      - PORT=3002
      - SELENIUM_ADDRESS=http://selenium:4444/wd/hub
      - MOCKSERVER_DOMAIN=mockserver
    tty: true
    env_file: ../../test.env
  mockserver:
    image: jamesdbloom/mockserver:mockserver-5.4.1
    ports:
      - 1080:1080
    tty: false
    logging:
      driver: "none"
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
    - 4444:4444
    - 5900
    links:
      - interface
    tty: false
    logging:
      driver: "none"